/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/beltradar/api/view/session/{public_id}/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Stats
         * @description Get session statistics for a specific public_id.
         *
         *     This Endpoint allows users to retrieve statistics of a specific survey session identified by its public_id.
         *     The user must have permission to access the survey session, and the survey session must exist.
         *
         *     Args:
         *         public_id (str): The public UUID of the survey session.
         *     Returns:
         *         200: A dictionary containing the survey session statistics in the API response format.
         *         403: An error message if the user does not have permission to access the survey session.
         *         404: An error message if the survey session is not found or not public.
         */
        get: operations["beltradar_api_session_get_session_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/my-sessions/{character_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Sessions
         * @description Get all sessions for the current user.
         *
         *     This Endpoint allows users to retrieve a list of all sessions associated with their character ID.
         *     The user must have permission to access the sessions.
         *
         *     Args:
         *         character_id (int): The character ID of the user.
         *     Returns:
         *         200: A list of sessions in the API response format.
         *         403: An error message if the user does not have permission to access the sessions.
         *         404: An error message if no sessions are found for the character.
         */
        get: operations["beltradar_api_session_get_my_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/public-sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Sessions
         * @description Get all sessions for the current user.
         *
         *     This Endpoint allows users to retrieve a list of all sessions that are visible to them.
         *     The user must have permission to access the sessions.
         *
         *     Returns:
         *         200: A list of sessions in the API response format.
         *         403: An error message if the user does not have permission to access the sessions.
         *         404: An error message if no sessions are found for the user.
         */
        get: operations["beltradar_api_session_get_public_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/session/add/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Session
         * @description Add a new session for the current user.
         *
         *     This Endpoint allows users to create a new session associated with their character ID.
         *     The user must have permission to create sessions.
         *
         *     Returns:
         *         200: A success message indicating the session was added.
         *         403: An error message if the user does not have permission to create sessions.
         *         400: An error message if the request data is invalid.
         */
        post: operations["beltradar_api_session_add_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/session/{public_id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Session
         * @description Delete an entire survey session and all its entries.
         *
         *     This Endpoint allows users to delete an entire survey session along with all its associated entries.
         *     The user must have permission to delete the survey session, and the survey session must exist.
         *
         *     Args:
         *         public_id (str): The public UUID of the survey session.
         *     Returns:
         *         200: A success message indicating the survey session was deleted.
         *         403: An error message if the user does not have permission or the session is not found.
         *         404: An error message if no entries are found for the given survey session.
         */
        post: operations["beltradar_api_session_delete_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/session/{public_id}/modify/{field}/value/{value}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Modify Session
         * @description Modify a specific session.
         *
         *     This Endpoint allows users to modify a specific session.
         *     The user must have permission to modify the session, and the session must exist.
         *
         *     Args:
         *         public_id (str): The public UUID of the session.
         *         field (str): The field of the session to modify.
         *         value (str): The new value to set for the specified field.
         *     Returns:
         *         200: A success message indicating the session was modified.
         *         403: An error message if the user does not have permission or the session is not found.
         *         404: An error message if the session does not exist.
         *         400: An error message if the request is malformed or invalid.
         */
        post: operations["beltradar_api_session_modify_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/session/{public_id}/snapshot/last_snapshot/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshot
         * @description Get the last snapshot for the given session.
         *
         *     Args:
         *         public_id (str): The public ID of the survey session.
         *     Returns:
         *         200: The last snapshot for the given session in the API response format.
         *         403: An error message if the user does not have permission to access the survey session.
         *         404: An error message if the survey session is not found.
         */
        get: operations["beltradar_api_snapshot_get_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/delete-snapshot/{public_id}/snapshot/{identifier}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Snapshot
         * @description Delete all survey entries for a specific snapshot in a survey session.
         *
         *     This Endpoint allows users to delete all entries associated with a specific snapshot timestamp within a survey session.
         *     The user must have permission to delete the survey session, and the survey session must exist.
         *
         *     Args:
         *         public_id (str): The public UUID of the survey session.
         *         identifier (str): The identifier of the snapshot to delete.
         *     Returns:
         *         200: A success message indicating the snapshot was deleted.
         *         403: An error message if the user does not have permission or the session is not found.
         *         404: An error message if no entries are found for the given snapshot.
         */
        post: operations["beltradar_api_snapshot_delete_snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/add-survey-entry/{public_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Snapshot
         * @description Add a snapshot to a session.
         *
         *     This Endpoint allows users to add a new snapshot to an existing session.
         *     The user must have permission to add snapshots to the session, and the session must exist.
         *
         *     Args:
         *         public_id (str): The public UUID of the session.
         *         parsed_data: A JSON object containing the snapshot data, including ore name, units, volume, price, timestamp, and snapshot identifier.
         *     Returns:
         *         200: A success message indicating the snapshot was added.
         *         400: An error message if the input data is invalid or cannot be parsed.
         *         403: An error message if the user does not have permission or the session is not found.
         *         404: An error message if the session is not found.
         */
        post: operations["beltradar_api_snapshot_add_snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/my-belt-timers/{character_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Belt Timer
         * @description Get belt timer details for the user's belt timer.
         *
         *     This Endpoint allows users to retrieve a list of all belt timers associated with their character ID.
         *     The user must have permission to access the belt timer, and the belt timer must exist.
         *
         *     Args:
         *         character_id (int): The character ID of the user.
         *     Returns:
         *         200: A list of belt timers in the API response format.
         *         403: An error message if the user does not have permission or the belt timer is not found.
         *         404: An error message if the belt timer is not found.
         */
        get: operations["beltradar_api_timer_get_my_belt_timer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/belt-timers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Belt Timers
         * @description Get belt timer details for public timers.
         *
         *     This Endpoint allows users to retrieve a list of all public belt timers.
         *     If the user is a superuser, they will receive all belt timers regardless of ownership.
         *
         *     Returns:
         *         200: A list of belt timers in the API response format.
         */
        get: operations["beltradar_api_timer_get_belt_timers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/belt-timer/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Belt Timer
         * @description Add a new belt timer to a survey session.
         *
         *     This Endpoint allows users to add a new belt timer to an existing survey session.
         *     The user must have permission to add entries to the survey session, and the survey session must exist.
         *
         *     Args:
         *         public_id (str): The public UUID of the survey session.
         *         parsed_data: A JSON object containing the belt timer data, including belt ID, belt name, belt type, ETA, and snapshot identifier.
         *     Returns:
         *         200: A success message indicating the belt timer was added.
         *         400: An error message if the input data is invalid or cannot be parsed.
         *         403: An error message if the user does not have permission or the survey session is not found.
         *         404: An error message if the survey session is not found.
         */
        post: operations["beltradar_api_timer_add_belt_timer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/belt-timer/{public_id}/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Session Belt Timer
         * @description Add a new survey timer to a survey session.
         *
         *     This Endpoint allows users to add a new survey timer to an existing survey session.
         *     The user must have permission to add entries to the survey session, and the survey session must exist.
         *
         *     Args:
         *         public_id (str): The public UUID of the survey session.
         *     Returns:
         *         200: A success message indicating the survey timer was added.
         *         400: An error message if the input data is invalid or cannot be parsed.
         *         403: An error message if the user does not have permission or the survey session is not found.
         *         404: An error message if the survey session is not found.
         */
        post: operations["beltradar_api_timer_add_session_belt_timer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/belt-timer/{timer_id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Belt Timer
         * @description Delete a specific belt timer in a survey session.
         *
         *     This Endpoint allows users to delete a specific belt timer within a survey session.
         *     The user must have permission to delete the survey session, and the survey session must exist.
         *
         *     Args:
         *         timer_id (int): The ID of the belt timer to delete.
         *     Returns:
         *         200: A success message indicating the belt timer was deleted.
         *         403: An error message if the user does not have permission or the session is not found.
         *         404: An error message if the belt timer is not found.
         */
        post: operations["beltradar_api_timer_delete_belt_timer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/manage/belt-timer/{timer_id}/modify/{field}/value/{value}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Modify Belt Timer
         * @description Modify a specific field of a belt timer in a survey session.
         *
         *     This Endpoint allows users to modify a specific field of a belt timer within a survey session.
         *     The user must have permission to modify the survey session, and the survey session must exist.
         *
         *     Args:
         *         timer_id (int): The ID of the belt timer to modify.
         *         field (str): The field of the belt timer to modify.
         *         value (str): The new value to set for the specified field.
         *     Returns:
         *         200: A success message indicating the belt timer was modified.
         *         400: An error message if the input data is invalid or cannot be parsed.
         *         403: An error message if the user does not have permission or the session is not found.
         *         404: An error message if the belt timer is not found.
         */
        post: operations["beltradar_api_timer_modify_belt_timer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Menu */
        get: operations["beltradar_api_menu_get_menu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["beltradar_api_general_get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/beltradar/api/view/action/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action */
        get: operations["beltradar_api_general_get_action"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionSchema
         * @description Schema for actions related to a session, including create, delete, and update actions.
         *
         *     Parameters:
         *         create (str | None): The action for creating a session.
         *         delete (str | None): The action for deleting a session.
         *         update (str | None): The action for updating a session.
         */
        ActionSchema: {
            create?: components["schemas"]["ModalSchema"] | null;
            delete?: components["schemas"]["ModalSchema"] | null;
            update?: components["schemas"]["ModalSchema"] | null;
        };
        /** DataTableSchema */
        DataTableSchema: {
            /** Raw */
            raw: unknown;
            /** Display */
            display: string;
            /** Sort */
            sort?: string | null;
            /** Translation */
            translation?: string | null;
            /** Dropdown Text */
            dropdown_text?: string | null;
        };
        /**
         * ModalSchema
         * @description Schema for modal dialog data.
         */
        ModalSchema: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Icon */
            icon: string;
            /** Modal Id */
            modal_id: string;
            /** Url */
            url: string;
            /** Color */
            color?: string | null;
            /** Buttontext */
            buttonText?: string | null;
        };
        /** OwnerSchema */
        OwnerSchema: {
            /**
             * Character Id
             * @default 0
             */
            character_id: number;
            /** Character Name */
            character_name?: string | null;
            /** Portrait */
            portrait?: string | null;
        };
        /** SessionSchema */
        SessionSchema: {
            /** Public Id */
            public_id: string;
            /** Name */
            name: string;
            owner: components["schemas"]["OwnerSchema"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            public: components["schemas"]["DataTableSchema"];
            /** First Timestamp */
            first_timestamp?: string | null;
            /** Last Timestamp */
            last_timestamp?: string | null;
            /** Total Timestamps */
            total_timestamps?: number | null;
            stats?: components["schemas"]["SessionStatsSchema"] | null;
            actions?: components["schemas"]["ActionSchema"] | null;
        };
        /** SessionStatsSchema */
        SessionStatsSchema: {
            /**
             * Belt Volume
             * @default 0
             */
            belt_volume: number;
            /**
             * Belt Volume Left M3
             * @default 0
             */
            belt_volume_left_m3: number;
            /**
             * Remaining Asteroids
             * @default 0
             */
            remaining_asteroids: number;
            /**
             * Total Asteroids
             * @default 0
             */
            total_asteroids: number;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
            /**
             * Mining Rate M3 Per S
             * @default 0
             */
            mining_rate_m3_per_s: number;
            /** Finish Eta */
            finish_eta?: string | null;
            /** Expected Belt Type */
            expected_belt_type?: string | null;
            /** Expected Belt Size */
            expected_belt_size?: string | null;
        };
        /** BeltSurveySessionSchema */
        BeltSurveySessionSchema: {
            /** Public Id */
            public_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            owner: components["schemas"]["OwnerSchema"];
            public: components["schemas"]["DataTableSchema"];
            actions?: components["schemas"]["ActionSchema"] | null;
            /** Html */
            html?: string | null;
        };
        /** ApexChartSchema */
        ApexChartSchema: {
            /**
             * Categories
             * @default []
             */
            categories: string[];
            /**
             * Series
             * @default []
             */
            series: components["schemas"]["ApexChartSeriesDataSchema"][];
        };
        /** ApexChartSeriesDataSchema */
        ApexChartSeriesDataSchema: {
            /** Name */
            name: string;
            /** Data */
            data: number[];
            /** Type */
            type?: string | null;
        };
        /** OreSchema */
        OreSchema: {
            /** Portrait */
            portrait?: string | null;
            /** Name */
            name: string;
            /** Units */
            units: number;
            /** Volume M3 */
            volume_m3: number;
            /** Price Isk */
            price_isk: number;
            /** Price Compressed */
            price_compressed?: number | null;
            /** Income Per H */
            income_per_h?: number | null;
            /** Income Cmp Per H */
            income_cmp_per_h?: number | null;
            /** Html */
            html?: string | null;
        };
        /** SnapShotDataSchema */
        SnapShotDataSchema: {
            /** Identifier */
            identifier: string;
            /** Last Timestamp */
            last_timestamp?: string | null;
            /** First Timestamp */
            first_timestamp?: string | null;
        };
        /** SnapShotSchema */
        SnapShotSchema: {
            snapshot?: components["schemas"]["SnapShotDataSchema"] | null;
            /** Ore List */
            ore_list?: components["schemas"]["OreSchema"][] | null;
            charts?: components["schemas"]["ApexChartSchema"] | null;
            traffic?: components["schemas"]["ApexChartSchema"] | null;
            actions?: components["schemas"]["ActionSchema"] | null;
        };
        /** BeltTimerSchema */
        BeltTimerSchema: {
            /** Public Id */
            public_id: string;
            /** Belt Id */
            belt_id: string;
            /** Belt Name */
            belt_name: string;
            /** Belt Size */
            belt_size: string;
            /** Belt Type */
            belt_type: string;
            eta: components["schemas"]["DataTableSchema"];
            public: components["schemas"]["DataTableSchema"];
            /** Is Expired */
            is_expired?: boolean | null;
            actions?: components["schemas"]["ActionSchema"] | null;
            /** Html */
            html?: string | null;
        };
        /**
         * MenuLink
         * @description Represents a link in the menu.
         *
         *     Parameters:
         *         name (str): The name of the menu link.
         *         link (str | None): The URL or path the menu link points to.
         */
        MenuLink: {
            /** Name */
            name: string;
            /** Link */
            link?: string;
        };
        /** MenuModalSchema */
        MenuModalSchema: {
            create_session?: components["schemas"]["ModalSchema"] | null;
            create_belt_timer?: components["schemas"]["ModalSchema"] | null;
            create_snapshot?: components["schemas"]["ModalSchema"] | null;
        };
        /** MenuSchema */
        MenuSchema: {
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["MenuLink"][];
            modals?: components["schemas"]["MenuModalSchema"] | null;
        };
        /**
         * UserData
         * @description Schema for user data, including character ID and character name.
         *
         *     Parameters:
         *         user_id (int): The ID of the user.
         *         character_id (int): The ID of the character associated with the user.
         *         character_name (str): The name of the character.
         *         portrait (str | None): The URL or path to the character's portrait image.
         *         notification (boolean): The notification status for the user.
         */
        UserData: {
            /** User Id */
            user_id: number;
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Portrait */
            portrait?: string | null;
            /** Notification */
            notification: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    beltradar_api_session_get_session_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_session_get_my_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeltSurveySessionSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_session_get_public_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeltSurveySessionSchema"][];
                };
            };
        };
    };
    beltradar_api_session_add_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_session_delete_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_session_modify_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
                field: string;
                value: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_snapshot_get_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapShotSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapShotSchema"];
                };
            };
        };
    };
    beltradar_api_snapshot_delete_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_snapshot_add_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_timer_get_my_belt_timer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeltTimerSchema"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_timer_get_belt_timers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeltTimerSchema"][];
                };
            };
        };
    };
    beltradar_api_timer_add_belt_timer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_timer_add_session_belt_timer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_timer_delete_belt_timer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_timer_modify_belt_timer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timer_id: number;
                field: string;
                value: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    beltradar_api_menu_get_menu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuSchema"];
                };
            };
        };
    };
    beltradar_api_general_get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
        };
    };
    beltradar_api_general_get_action: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionSchema"];
                };
            };
        };
    };
}
