# Generated by Django 5.2.13 on 2026-05-18 19:42

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0001_initial"),
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveMarketPrice",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "eve_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "adjusted_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
