# Generated by Django 5.2.13 on 2026-05-25 16:34

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0002_evemarketprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltsurveysession",
            name="name",
            field=models.CharField(default="Unnamed Session", max_length=150),
            preserve_default=False,
        ),
    ]
