# Generated by Django 5.2.13 on 2026-07-13 16:12

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0003_alter_beltsurveysession_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltsurveysession",
            name="public_id",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
