# Generated by Django 5.2.13 on 2026-07-13 17:41

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("beltradar", "0004_alter_beltsurveysession_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beltsurveyentry",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="beltsurveysession",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="br_user_sessions",
                to="authentication.user",
            ),
        ),
    ]
