# Generated by Django 5.2.13 on 2026-07-31 09:46

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("beltradar", "0005_alter_beltsurveyentry_recorded_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltTimer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("belt_id", models.CharField(max_length=7)),
                ("belt_name", models.CharField(max_length=100)),
                (
                    "belt_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("enormous", "Enormous"),
                            ("colossal", "Colossal"),
                            ("ice", "Ice"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "belt_type",
                    models.CharField(
                        choices=[
                            ("asteroid_belt", "Asteroid Belt"),
                            ("ice_belt", "Ice Belt"),
                            ("mercobelt", "Mercocit Belt"),
                            ("arrey_belt", "Arrey Belt"),
                        ],
                        max_length=15,
                    ),
                ),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("sent_notification", models.BooleanField(default=False)),
                (
                    "session",
                    models.ManyToManyField(
                        related_name="br_timer", to="beltradar.beltsurveysession"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disable_notifications", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
