# Generated by Django 5.2.13 on 2026-08-03 08:24

# Standard Library
import uuid

# Django
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def copy_timer_owner_from_session(apps, schema_editor):
    """Populate BeltTimer.owner from the related BeltSurveySession owner.

    BeltTimer previously used an M2M relation named `session`. During this
    migration we move ownership to a direct FK. Timers without any related
    session are removed because they cannot be owned reliably.
    """

    BeltTimer = apps.get_model("beltradar", "BeltTimer")

    for timer in BeltTimer.objects.all().iterator():
        session = timer.session.order_by("id").first()
        if session and session.owner_id:
            timer.owner_id = session.owner_id
            timer.save(update_fields=["owner"])
            continue

        timer.delete()


def populate_timer_public_ids(apps, schema_editor):
    """Backfill public IDs for existing belt timers after the field exists."""

    BeltTimer = apps.get_model("beltradar", "BeltTimer")
    existing_ids = set(
        BeltTimer.objects.exclude(public_id__isnull=True)
        .exclude(public_id="")
        .values_list("public_id", flat=True)
    )

    for timer in BeltTimer.objects.filter(
        Q(public_id__isnull=True) | Q(public_id="")
    ).iterator():
        public_id = uuid.uuid4().hex[:12]

        while public_id in existing_ids:
            public_id = uuid.uuid4().hex[:12]

        existing_ids.add(public_id)
        timer.public_id = public_id
        timer.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("beltradar", "0006_belttimer_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="belttimer",
            name="owner",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="br_user_timers",
                to="authentication.user",
            ),
        ),
        migrations.RunPython(copy_timer_owner_from_session, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="belttimer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="br_user_timers",
                to="authentication.user",
            ),
        ),
        migrations.RemoveField(
            model_name="belttimer",
            name="session",
        ),
        migrations.AddField(
            model_name="belttimer",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="belttimer",
            name="public_id",
            field=models.CharField(default="", max_length=36),
        ),
        migrations.RunPython(populate_timer_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="beltsurveysession",
            name="public_id",
            field=models.CharField(default="", max_length=36),
        ),
    ]
