# Generated by Django 5.2.13 on 2026-08-03 08:24

# Django
import django.db.models.deletion
from django.db import migrations, models

# AA Belt Radar
import beltradar.models.beltradar


def copy_timer_owner_from_session(apps, schema_editor):
    """Populate BeltTimer.owner from the related BeltSurveySession owner.

    BeltTimer previously used an M2M relation named `session`. During this
    migration we move ownership to a direct FK. Timers without any related
    session are removed because they cannot be owned reliably.
    """

    BeltTimer = apps.get_model("beltradar", "BeltTimer")

    for timer in BeltTimer.objects.all().iterator():
        session = timer.session.order_by("id").first()
        if session and session.owner_id:
            timer.owner_id = session.owner_id
            timer.save(update_fields=["owner"])
            continue

        timer.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("beltradar", "0006_belttimer_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="belttimer",
            name="owner",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="br_user_timers",
                to="authentication.user",
            ),
        ),
        migrations.RunPython(copy_timer_owner_from_session, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="belttimer",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="br_user_timers",
                to="authentication.user",
            ),
        ),
        migrations.RemoveField(
            model_name="belttimer",
            name="session",
        ),
        migrations.AddField(
            model_name="belttimer",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="belttimer",
            name="public_id",
            field=models.CharField(
                max_length=36,
                default=beltradar.models.beltradar.generate_unique_public_id,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="beltsurveysession",
            name="public_id",
            field=models.CharField(
                max_length=36,
                default=beltradar.models.beltradar.generate_unique_public_id,
                editable=False,
                unique=True,
            ),
        ),
    ]
