# Generated by Django 5.2.13 on 2026-08-31 16:54

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0007_remove_belttimer_session_belttimer_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="belttimer",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a survey session for this belt timer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="br_belt_timer",
                to="beltradar.beltsurveysession",
            ),
        ),
    ]
