# Generated by Django 5.2.13 on 2026-09-04 13:10

# Django
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _sanatize_survey_entry(apps, schema_editor):
    BeltSurveyEntry = apps.get_model("beltradar", "BeltSurveyEntry")
    BeltSurveySession = apps.get_model("beltradar", "BeltSurveySession")

    # Delete all Entries & Sessions
    BeltSurveyEntry.objects.all().delete()
    BeltSurveySession.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("beltradar", "0008_belttimer_session"),
        ("eve_sde", "0036_remove_star_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltSurveySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=12)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("asteroids", models.ManyToManyField(to="beltradar.beltsurveyentry")),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.user",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="br_snapshots",
                        to="beltradar.beltsurveysession",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.RunPython(
            code=_sanatize_survey_entry, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name="beltsurveyentry",
            options={"default_permissions": ()},
        ),
        migrations.RemoveField(
            model_name="beltsurveyentry",
            name="recorded_by",
        ),
        migrations.RemoveField(
            model_name="beltsurveyentry",
            name="session",
        ),
        migrations.RemoveField(
            model_name="beltsurveyentry",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="beltsurveyentry",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eve_sde.itemtype"
            ),
        ),
        migrations.AlterField(
            model_name="belttimer",
            name="belt_type",
            field=models.CharField(
                choices=[
                    ("asteroid_belt", "Asteroid Belt"),
                    ("ice_belt", "Ice Belt"),
                    ("mercoxit", "Mercoxit Belt"),
                    ("array_belt", "Array Belt"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="belttimer",
            name="sent_notification",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether a notification has been sent for this timer.",
            ),
        ),
        migrations.AlterField(
            model_name="beltsurveyentry",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="br_asteroids",
                to="beltradar.beltsurveysnapshot",
            ),
        ),
        migrations.RenameField(
            model_name="belttimer",
            old_name="public",
            new_name="is_public",
        ),
        migrations.AddField(
            model_name="beltsurveysession",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this session is publicly accessible without public id.",
            ),
        ),
    ]
