# Generated by Django 5.2.13 on 2026-09-05 12:33

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0009_refactor_beltradar"),
    ]

    operations = [
        migrations.AddField(
            model_name="beltsurveysession",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this session is publicly accessible without public id.",
            ),
        ),
    ]
