# Generated by Django 5.2.13 on 2026-09-07 14:26

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0010_alter_belttimer_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="belttimer",
            name="session",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional link to a session for this belt timer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="br_belt_timer",
                to="beltradar.beltsurveysession",
            ),
        ),
    ]
