# Generated by Django 5.2.13 on 2026-09-05 12:58

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0010_beltsurveysession_is_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="belttimer",
            old_name="public",
            new_name="is_public",
        ),
    ]
