# Generated by Django 5.2.13 on 2026-09-20 14:04

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beltradar", "0011_alter_belttimer_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app, Belt Radar"),
                    ("manage_access", "Can manage Belt Radar"),
                    ("admin_access", "Admin access to Belt Radar"),
                ),
                "verbose_name": "AA-Belt-Radar",
                "verbose_name_plural": "AA-Belt-Radar",
            },
        ),
    ]
